module.exports = function bannerLoader(source) {
  const options = this.getOptions() || {};
  const banner = options.banner || "Generated by banner-loader";
  const normalized = String(banner).replace(/\*\//g, "* /");
  return `/* ${normalized} */\n${source}`;
};
